### ISSUE TITLE
Fluky Test: ConcurrentModificationException triggered by liquibase.executor.ExecutorService

### ISSUE THREAD

**Issue by Treehopper** [Treehopper/liquibase-lsp#1]
Occurs in ~20% of test runs

```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
        at liquibase.executor.ExecutorService.getExecutor(ExecutorService.java:93)
        at liquibase.snapshot.SnapshotGeneratorFactory.has(SnapshotGeneratorFactory.java:114)
        at liquibase.snapshot.SnapshotGeneratorFactory.hasDatabaseChangeLogTable(SnapshotGeneratorFactory.java:272)
        at liquibase.changelog.StandardChangeLogHistoryService.hasDatabaseChangeLogTable(StandardChangeLogHistoryService.java:88)
        at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:310)
        at liquibase.database.AbstractJdbcDatabase.getRanChangeSetList(AbstractJdbcDatabase.java:1123)
        at org.eclipse.lemminx.liquibase.validation.wrapper.ValidationWrappingDatabaseChangeLog.validate(ValidationWrappingDatabaseChangeLog.java:48)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:264)
        at org.eclipse.lemminx.liquibase.validation.wrapper.FailureResilientLiquibase.validate(FailureResilientLiquibase.java:62)
        at org.eclipse.lemminx.liquibase.validation.Validator.doDiagnostics(Validator.java:104)
        at org.eclipse.lemminx.liquibase.DiagnosticsParticipant.doDiagnostics(DiagnosticsParticipant.java:46)
        at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
        at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
        at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:152)
        at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:161)
        at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:464)
        at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:457)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Treehopper** [comment]
Seems like this was fixed here: https://github.com/liquibase/liquibase/issues/1402
